# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceef6385a5c506a86473c90713d5872e620058dc27fc6d12352a8431c23951e84ffc6bb3ca461440c8421474b455fb620632fec92984f9fbe66573a47d6da52b

test:
  secret_key_base: c49f49ab77c1ee11a8b3526c777c5b26b7f16dc6e16b06b79a337ee309eeaf6630d6ad5a62748d408e46fde7909aa9609b7d2265032a7f7f8da21293496256a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
